runtime: python27
api_version: 1
threadsafe: yes

handlers:

- url: /css
  static_dir: css
  secure: always

- url: /js
  static_dir: js
  secure: always

- url: /
  static_files: index.html
  upload: index.html

- url: /(.+)
  static_files: \1.html
  upload: (.+)
